### ISSUE TITLE
when will the code be released？

### ISSUE THREAD

**Issue by hrz2000** [JunzheJosephZhu/HiFA#1]
tks for your great work, i'm looking forward to the code.

**Comment by ninjasaid2k** [comment]
I'm wondering this too

**Comment by JunzheJosephZhu** [comment]
will release in about a month or two

**Comment by HiFA-team** [comment]
will release in about a month or two

**Comment by milkywaystars** [comment]
> will release in about a month or two

Hi HiFA-Team. It been 2 months. Are you guys close to releasing yet? Please let us know if there is a delay.

**Comment by ninjasaid2k** [comment]
I think there has been a delay.
