### ISSUE TITLE
Questions on Timestep annealing.

### ISSUE THREAD

**Issue by Colezwhy** [JunzheJosephZhu/HiFA#11]
Thank you for your great work!
And I wonder where the 'timestep annealing' part in paper is implemented in the provided code?  I wanted to check how to implement that.
Much thanks!

**Comment by JunzheJosephZhu** [comment]
https://github.com/JunzheJosephZhu/HiFA/blob/1bbe86135f960f4f99ab1f4c294bb5f4151da273/nerf/sd.py#L219
